name: formdev
description: "A new Flutter project."
publish_to: 'none'
version: 3.0.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  # dependencies tambahan taruk disini
  msix: ^3.16.13
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
